import 'dart:ui';
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_typography.dart';
import '../../../core/utils/formatters.dart';
import '../../../data/models/analysis_result.dart';
import '../../../core/l10n/app_localizations.dart';
import '../../viewmodels/app_viewmodel.dart';
import '../../widgets/glass_panel.dart';
import '../../widgets/speaker_badge.dart';

class AnalysisDetailScreen extends StatelessWidget {
  final AnalysisResult result;
  const AnalysisDetailScreen({super.key, required this.result});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      appBar: AppBar(
        backgroundColor: AppColors.zinc950.withValues(alpha: 0.8),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back, color: AppColors.primaryContainer),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text('NEURAL_CORE', style: AppTypography.labelCaps.copyWith(color: AppColors.primaryContainer, fontSize: 14, letterSpacing: 3)),
        actions: [
          Padding(padding: const EdgeInsets.only(right: 8), child: Text('ANALYSIS', style: AppTypography.labelCaps.copyWith(color: AppColors.zinc500, fontSize: 11))),
          const Padding(padding: EdgeInsets.only(right: 16), child: Icon(Icons.settings_input_component, color: AppColors.primaryContainer, size: 24)),
        ],
        flexibleSpace: ClipRect(child: BackdropFilter(filter: ImageFilter.blur(sigmaX: 20, sigmaY: 20), child: Container(color: Colors.transparent))),
        bottom: PreferredSize(preferredSize: const Size.fromHeight(1), child: Container(height: 1, color: Colors.white.withValues(alpha: 0.1))),
      ),
      body: SafeArea(
        child: SingleChildScrollView(
          padding: const EdgeInsets.fromLTRB(24, 24, 24, 40),
          child: Builder(builder: (context) {
            final l = context.read<AppViewModel>().l10n;
            return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
              _buildMetadata(l), const SizedBox(height: 32),
              _buildTranscription(l), const SizedBox(height: 24),
              _buildAISummary(l), const SizedBox(height: 16),
              if (result.emailDeliveryStatus != null) _buildDelivery(l),
            ]);
          }),
        ),
      ),
    );
  }

  Widget _buildMetadata(AppLocalizations l) {
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(children: [
        const Icon(Icons.memory, size: 18, color: AppColors.primaryFixedDim),
        const SizedBox(width: 8),
        Text('RECORDING_${result.id.length > 3 ? result.id.substring(0, 3).toUpperCase() : result.id.toUpperCase()}', style: AppTypography.labelCaps.copyWith(color: AppColors.primaryFixedDim, letterSpacing: 2.4)),
      ]),
      const SizedBox(height: 12),
      Text(result.title, style: AppTypography.h1.copyWith(color: AppColors.onBackground)),
      const SizedBox(height: 12),
      Wrap(spacing: 16, runSpacing: 8, children: [
        _meta(Icons.calendar_today, Formatters.formatDateFull(result.date)),
        _meta(Icons.schedule, Formatters.formatDurationShort(result.duration)),
        _meta(Icons.group, '${result.participantCount} ${l.participants}'),
      ]),
    ]);
  }

  Widget _meta(IconData icon, String text) => Row(mainAxisSize: MainAxisSize.min, children: [
    Icon(icon, size: 16, color: AppColors.onSurfaceVariant), const SizedBox(width: 4),
    Text(text, style: AppTypography.bodyMd.copyWith(color: AppColors.onSurfaceVariant)),
  ]);

  Widget _buildTranscription(AppLocalizations l) {
    return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [
        Text(l.transcription, style: AppTypography.h3.copyWith(color: AppColors.onBackground)),
        Container(padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4), decoration: BoxDecoration(color: AppColors.surfaceContainer, borderRadius: BorderRadius.circular(4)),
          child: Text(l.autoGenerated, style: AppTypography.labelCaps.copyWith(color: AppColors.onSurfaceVariant))),
      ]),
      Divider(color: AppColors.outlineVariant, height: 24),
      Container(
        constraints: const BoxConstraints(maxHeight: 400),
        padding: const EdgeInsets.all(24),
        decoration: BoxDecoration(color: AppColors.surfaceContainerLow, borderRadius: BorderRadius.circular(8), border: Border.all(color: AppColors.outlineVariant)),
        child: result.transcript.isEmpty
            ? Center(child: Text(l.transcriptPending, style: AppTypography.bodyMd.copyWith(color: AppColors.onSurfaceVariant)))
            : ListView.separated(shrinkWrap: true, itemCount: result.transcript.length, separatorBuilder: (c, idx) => const SizedBox(height: 16),
                itemBuilder: (_, i) {
                  final b = result.transcript[i];
                  final sNum = int.tryParse(b.speaker.replaceAll(RegExp(r'[^0-9]'), '')) ?? i;
                  return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                    Row(children: [SpeakerBadge(speaker: b.speaker, speakerIndex: sNum), const SizedBox(width: 8), Text(Formatters.formatTimestamp(b.timestamp), style: AppTypography.mono.copyWith(color: AppColors.onSurfaceVariant))]),
                    const SizedBox(height: 8),
                    Text(b.text, style: AppTypography.bodyMd.copyWith(color: AppColors.onBackground, height: 1.6)),
                  ]);
                }),
      ),
    ]);
  }

  Widget _buildAISummary(AppLocalizations l) {
    return GlassPanel(borderColor: AppColors.primaryFixedDim, borderOpacity: 0.4, child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
      Row(children: [const Icon(Icons.auto_awesome, color: AppColors.primaryFixedDim, size: 24), const SizedBox(width: 8), Text(l.aiSummary, style: AppTypography.h3.copyWith(color: AppColors.primaryFixedDim))]),
      const SizedBox(height: 16),
      Text(
        result.summary.isNotEmpty ? result.summary : l.noSummary,
        style: AppTypography.bodyMd.copyWith(color: AppColors.onSurface),
      ),
      if (result.actionItems.isNotEmpty) ...[
        const SizedBox(height: 16),
        Text(l.actionItems, style: AppTypography.labelCaps.copyWith(color: AppColors.primaryFixedDim, letterSpacing: 1.5)),
        const SizedBox(height: 8),
        ...result.actionItems.map((item) => Padding(padding: const EdgeInsets.only(bottom: 8), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [
          const Padding(padding: EdgeInsets.only(top: 2), child: Icon(Icons.radio_button_checked, size: 16, color: AppColors.tertiaryFixedDim)),
          const SizedBox(width: 8), Expanded(child: Text(item, style: AppTypography.bodyMd.copyWith(color: AppColors.onSurface))),
        ]))),
      ],
    ]));
  }

  Widget _buildDelivery(AppLocalizations l) {
    return Container(padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: AppColors.surfaceContainerHigh, borderRadius: BorderRadius.circular(8), border: Border.all(color: AppColors.outlineVariant)),
      child: Row(children: [
        Container(width: 40, height: 40, decoration: BoxDecoration(shape: BoxShape.circle, color: AppColors.surfaceContainerLowest, border: Border.all(color: AppColors.outline)),
          child: const Icon(Icons.mail, color: AppColors.onSurfaceVariant, size: 20)),
        const SizedBox(width: 16),
        Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
          Text(l.deliveryStatus, style: AppTypography.labelCaps.copyWith(color: AppColors.onSurfaceVariant)),
          const SizedBox(height: 2),
          Text(result.emailDeliveryStatus ?? '', style: AppTypography.bodyMd.copyWith(color: AppColors.onBackground)),
        ])),
        const Icon(Icons.check_circle, color: AppColors.primaryContainer, size: 24),
      ]));
  }
}
